$shellscript = <<-SCRIPT
  echo "Running setupScript.sh"
  cd /vagrant
  sudo chmod +x setupScript.sh
  ./setupScript.sh
SCRIPT

Vagrant.configure('2') do |config|
  config.ssh.forward_agent = true
  config.ssh.shell="bash"
  config.vm.provision "shell", inline: $shellscript
  config.vm.define "DOPingMarker" do |config|
      config.vm.provider :digital_ocean do |provider, override|
        override.ssh.private_key_path = '~/.ssh/id_rsa'
        override.vm.box = 'digital_ocean'
        override.vm.box_url = "https://github.com/devopsgroup-io/vagrant-digitalocean/raw/master/box/digital_ocean.box"
        override.nfs.functional = false
        override.vm.allowed_synced_folder_types = :rsync
        provider.ssh_key_name = ENV['DOTOKENNAME']
        provider.token = ENV['DOTOKEN'] || ''
        provider.image = 'ubuntu-16-04-x64'
        provider.region = ENV['DOREGION'] || 'LON1'
        provider.size = '2gb'
      end
  end
end
